apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: eoap-mastering-app-package
    
deploy:
  helm:
    releases:
      - name: dev-platform-eoap
        chartPath: charts/coder
        namespace: dev-platform-eoap
        createNamespace: true
        setValues:
          coder.storageClassName: standard
          coder.workspaceStorage: 10Gi
          coderResources.limits.cpu: '2'
          coderResources.limits.memory: '6442450944'
          coderResources.requests.cpu: '1'
          coderResources.requests.memory: '4294967296'
          calrissian.enabled: true
          calrissian.imagePullSecrets: []
        setFiles: {
          initScript: ./files/init.sh,
          bashrcScript: ./files/bash-rc,
          bashloginScript: ./files/bash-login
        }

portForward:
  - resourceType: service
    resourceName: code-server-service
    namespace: dev-platform-eoap
    address: localhost
    port: 8080
    localPort: 8000

profiles:

  - name: eodh

    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues/coder.storageClassName
        value: "file-storage"
      - op: add
        path: /deploy/helm/releases/0/setValues/calrissian.storageClassName
        value: "file-storage"