version: '3'

tasks:
  submit-k8s-job:
    desc: "Submit water bodies detection job to Kubernetes cluster"
    cmds:
      - kubectl apply -f water-bodies-cloud-native-k8s-job.yaml

  run-calrissian:
    desc: "Run Calrissian locally"
    vars:
      WORKFLOW_ID: '{{.WORKFLOW_ID | default "water-bodies"}}'
      WORKFLOW: '{{.WORKFLOW | default "/workspace/getting-started/app-water-bodies-cloud-native.1.1.0.cwl"}}'
      WORKFLOW_PARAMS: '{{.WORKFLOW_PARAMS | default "/calrissian/params.yaml"}}'
    cmds:
      - |
        calrissian \
            --stdout \
            /calrissian/{{.WORKFLOW_ID}}/results.json \
            --stderr \
            /calrissian/{{.WORKFLOW_ID}}/log.json \
            --pod-serviceaccount \
            calrissian-sa \
            --max-ram \
            4G \
            --max-cores \
            "8" \
            --tmp-outdir-prefix \
            /calrissian/tmp/ \
            --outdir \
            /calrissian/{{.WORKFLOW_ID}}/results \
            --usage-report \
            /calrissian/{{.WORKFLOW_ID}}/usage.json \
            --tool-logs-basepath \
            /calrissian/tool-logs \
            --pod-nodeselectors \
            /calrissian/pod-node-selector.yaml \
            /calrissian/{{.WORKFLOW}}#{{.WORKFLOW_ID}} \
            /calrissian/{{.WORKFLOW_PARAMS}}

  wrap: 
    desc: "Wrap CWL workflow with stage-in/stage-out steps"
    vars:
      WORKFLOW_ID: '{{.WORKFLOW_ID | default "water-bodies"}}'
      WORKFLOW: '{{.WORKFLOW | default "/workspace/getting-started/water-bodies-cloud-native.1.1.0.cwl"}}'
    cmds:
      - |
        cwl-wrapper \
          -c ~/.cwlwrapper/default.conf \
          --workflow-id {{.WORKFLOW_ID}} \
          {{.WORKFLOW}}